FROM daocloud.io/grissomsh/maven:latest

MAINTAINER Grissom Wang <grissom.wang@daocloud.io>

ENV TIME_ZONE Asia/Shanghai

RUN echo "$TIME_ZONE" > /etc/timezone

WORKDIR /app

COPY . /app

CMD ["mvn", "package"]